In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\DELL
[nltk_data]     INDIA\AppData\Roaming\nltk_data...
[nltk_data] Error downloading 'punkt' from
[nltk_data]     <https://raw.githubusercontent.com/nltk/nltk_data/gh-
[nltk_data]     pages/packages/tokenizers/punkt.zip>:   <urlopen error
[nltk_data]     [WinError 10060] A connection attempt failed because
[nltk_data]     the connected party did not properly respond after a
[nltk_data]     period of time, or established connection failed
[nltk_data]     because connected host has failed to respond>


False

In [16]:
import re
import nltk
nltk.download('stopwords')
from nltk.util import pr
stemmer=nltk.SnowballStemmer("english")
from nltk.corpus import stopwords
nltk.download('wordnet')
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
from wordcloud import WordCloud
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
import string
stopword=set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to C:\Users\DELL
[nltk_data]     INDIA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\DELL
[nltk_data]     INDIA\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [17]:
df=pd.read_csv("twitter_data.csv")
# print(df.head())
print(df.shape)

(24783, 7)


In [18]:
df['labels']=df['class'].map({0:"Hate Speech Detected",1:"Offensive language detected",2:"No hate and offensive speech"})
print(df.head())

   Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  \
0  !!! RT @mayasolovely: As a woman you shouldn't...   
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   

                         labels  
0  No hate and offensive speech  
1   Offensive language detected  
2   Offensive language detected  
3   Offensive language detected  
4   Offensive language detected  


In [19]:
df=df[['tweet','labels']]
df.head()

tweet  \
0  !!! RT @mayasolovely: As a woman you shouldn't...   
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   

                         labels  
0  No hate and offensive speech  
1   Offensive language detected  
2   Offensive language detected  
3   Offensive language detected  
4   Offensive language detected

In [21]:
#creating a function to process the data
def clean(tweet):
    tweet = str(tweet).lower()
    tweet = re.sub(r"https\S+|www\S+http\S+", '', tweet, flags = re.MULTILINE)
    tweet = re.sub(r'\@w+|\#','', tweet)
    tweet = re.sub(r'[^\w\s]','',tweet)
    tweet = re.sub(r'ð','',tweet)
    tweet_tokens = word_tokenize(tweet)
    filtered_tweets = [w for w in tweet_tokens if not w in stop_words]
    return " ".join(filtered_tweets)
df["tweet"]=df["tweet"].apply(clean)
# print(df.head())

LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/english.pickle

  Searched in:
    - 'C:\\Users\\DELL INDIA/nltk_data'
    - 'C:\\Users\\DELL INDIA\\AppData\\Local\\Programs\\Python\\Python39\\nltk_data'
    - 'C:\\Users\\DELL INDIA\\AppData\\Local\\Programs\\Python\\Python39\\share\\nltk_data'
    - 'C:\\Users\\DELL INDIA\\AppData\\Local\\Programs\\Python\\Python39\\lib\\nltk_data'
    - 'C:\\Users\\DELL INDIA\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - ''
**********************************************************************


In [22]:
df = df.drop_duplicates('tweet')

In [23]:
lemmatizer = WordNetLemmatizer()
def lemmatizing(data):
    tweet = [lemmatizer.lemmatize(word) for word in data]
    return data

In [24]:
df['tweet'] = df['tweet'].apply(lambda x: lemmatizing(x))

In [25]:
df['labels'].value_counts()

Offensive language detected     19190
No hate and offensive speech     4163
Hate Speech Detected             1430
Name: labels, dtype: int64

In [26]:
fig = plt.figure(figsize=(5,5))
sns.countplot(x='labels', data = df)

NameError: name 'sns' is not defined

<Figure size 500x500 with 0 Axes>

In [ ]:
vect = TfidfVectorizer(ngram_range=(1,2)).fit(df['tweet'])

In [ ]:
feature_names = vect.get_feature_names_out() 
print("Number of features: {}\n".format(len(feature_names)))
print("First 20 features: \n{}".format(feature_names[:20]))

In [ ]:
vect = TfidfVectorizer(ngram_range=(1,3)).fit(df['tweet'])

In [48]:
feature_names = vect.get_feature_names_out()
print("Number of features: {}\n".format(len(feature_names)))
print("First 20 features: \n{}".format(feature_names[:20]))

Number of features: 355237

First 20 features: 
['007' '007 httptcoon5t60rmfb' '007beardownjedi' '007beardownjedi afl'
 '007beardownjedi afl american' '007hertzrumble'
 '007hertzrumble httptcoqyn1bc7mxs' '007hertzrumble httptcoqyn1bc7mxs via'
 '007m_h' '007m_h lilduval' '007m_h lilduval damn' '00_jackie'
 '00_jackie darknight420' '00_jackie darknight420 allahthefairy'
 '00_jackie wan' '00_jackie wan na' '00sexilexi00' '00sexilexi00 bitch'
 '00sexilexi00 bitch ass' '00sexilexi00 freeze']


In [49]:
X = df['tweet']
Y = df['labels']
X = vect.transform(X)
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)     

In [50]:
print("Size of x_train:", (x_train.shape))
print("Size of y_train:", (y_train.shape))
print("Size of x_test: ", (x_test.shape))
print("Size of y_test: ", (y_test.shape))

Size of x_train: (19758, 355237)
Size of y_train: (19758,)
Size of x_test:  (4940, 355237)
Size of y_test:  (4940,)


In [51]:
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
clf_predict = clf.predict(x_test)
clf_acc = accuracy_score(clf_predict, y_test)
print("Test accuarcy: {:.2f}%".format(clf_acc*100))

Test accuarcy: 88.00%


In [52]:
print(confusion_matrix(y_test, clf_predict))
print("\n")
print(classification_report(y_test, clf_predict))

[[  53   34  196]
 [  22  738  103]
 [  94  144 3556]]


                              precision    recall  f1-score   support

        Hate Speech Detected       0.31      0.19      0.23       283
No hate and offensive speech       0.81      0.86      0.83       863
 Offensive language detected       0.92      0.94      0.93      3794

                    accuracy                           0.88      4940
                   macro avg       0.68      0.66      0.66      4940
                weighted avg       0.87      0.88      0.87      4940



In [15]:
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
logreg_predict = logreg.predict(x_test)
logreg_acc = accuracy_score(logreg_predict, y_test)
print("Test accuarcy: {:.2f}%".format(logreg_acc*100))

NameError: name 'x_train' is not defined

In [ ]:
print(confusion_matrix(y_test, logreg_predict))
print("\n")
print(classification_report(y_test, logreg_predict))

In [ ]:
from matplotlib import style
style.use('classic')
cm = confusion_matrix(y_test, logreg_predict, labels=logreg.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=logreg.classes_)
disp.plot()

In [ ]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [ ]:
test_data="You are nice"
df=vect.transform([test_data]).toarray()
print(clf.predict(df))

In [9]:
test_data="you are bad"
df=vect.transform([test_data])
print(logreg.predict(df))

NameError: name 'vect' is not defined